name: Block Unsafe PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  prevent-unsafe-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Source Branch
        run: |
          echo "🔍 Checking if PR comes from 'preprod'..."
          echo "PR head: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "preprod" ]]; then
            echo "❌ Pull requests to 'main' are only allowed from 'preprod'!"
            exit 1
          else
            echo "✅ PR source branch is 'preprod' — proceeding."
          fi
